name: Continuous Integration

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - { name: "MSVC 14.3 - C++20", os: windows-2022, cxxstd: '17,20', cmake_args: -G "Visual Studio 17 2022" -A x64, }
          - { name: "MSVC 14.2 - C++17", os: windows-2019, cxxstd: 17, cmake_args: -G "Visual Studio 16 2019" -A x64, }

          - { name: "GCC 12 - C++20",    os: ubuntu-22.04, cc: gcc-12, cxx: g++-12, cxxstd: '17,20', }
          - { name: "GCC 11 - C++20",    os: ubuntu-22.04, cc: gcc-11, cxx: g++-11, cxxstd: 20, }
          - { name: "GCC 10 - C++20",    os: ubuntu-22.04, cc: gcc-10, cxx: g++-10, cxxstd: 20, }
          - { name: "GCC 9  - C++20",    os: ubuntu-22.04, cc: gcc-9,  cxx: g++-9,  cxxstd: 20, }
          - { name: "GCC 8  - C++17",    os: ubuntu-20.04, cc: gcc-8,  cxx: g++-8,  cxxstd: 17, install: g++-8, }
          - { name: "GCC 7  - C++14",    os: ubuntu-20.04, cc: gcc-7,  cxx: g++-7,  cxxstd: 14, install: g++-7, }

          - { name: "Clang 14 - C++20",  os: ubuntu-22.04, cc: clang-14, cxx: clang++-14, cxxstd: 20, }
          - { name: "Clang 13 - C++17",  os: ubuntu-22.04, cc: clang-13, cxx: clang++-13, cxxstd: 17, }
          - { name: "Clang 12 - C++20",  os: ubuntu-22.04, cc: clang-12, cxx: clang++-12, cxxstd: 20, }
          - { name: "Clang 11 - C++17",  os: ubuntu-20.04, cc: clang-11, cxx: clang++-11, cxxstd: 17, install: clang-11, }

          - { name: "AppleClang 13",     os: macos-12,     cxxstd: 17 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/package_install
        id: package-install
        with:
          vcpkg: fmt,openssl,zlib
          apt-get: ${{ matrix.install }}

      - name: Boost Clone
        uses: ./.github/actions/boost_clone
        with:
          boost_dir: boost
          branch: ${{ (startsWith(github.ref, 'refs/heads/master') && 'master') || 'develop' }}
          patches: https://github.com/CppAlliance/buffers.git,https://github.com/CppAlliance/http_proto.git,https://github.com/CppAlliance/http_io.git
          modules: url,../../../BoostServerTech

      - name: CMake Run (C++${{ matrix.cxxstd }})
        uses: ./.github/actions/cmake_run
        with:
          toolchain: ${{ steps.package-install.outputs.vcpkg_toolchain }}
          cxxstd: ${{ matrix.cxxstd }}
          cxx: ${{ matrix.cxx }}
          cc: ${{ matrix.cc }}
          extra-args: ${{ format('-D BOOST_ROOT=boost {0}', matrix.cmake_args) }}

